version: 0.2

phases:
  build:
    commands:
      - npm install
  post_build:
      commands:
        - mkdir build-output
        - cp -R index.js node_modules/ build-output
artifacts:
  files:
    - build-output/**/*